version: '3'

services:
  # webdriverio:
  #   build: .
  #   depends_on:
  #     - chrome
  #     - selenium-hub
  #   volumes:
  #    - ./app:/app
  #   environment:
  #   - HUB_PORT_4444_TCP_ADDR=selenium-hub
  #    - HUB_PORT_4444_TCP_PORT=4444

  chrome:
    image: selenium/node-chrome:4.1.0-prerelease-20211105
    shm_size: 2gb
    depends_on:
      - selenium-hub
    scale: 2
    environment:
      - SE_EVENT_BUS_HOST=selenium-hub
      - SE_EVENT_BUS_PUBLISH_PORT=4442
      - SE_EVENT_BUS_SUBSCRIBE_PORT=4443
      - SCREEN_WIDTH=1920
      - SCREEN_HEIGHT=1080
    #ports:
    # - '5555'

  selenium-hub:
    image: selenium/hub:4.1.0-prerelease-20211105
    container_name: selenium-hub
    ports:
      - '4442:4442'
      - '4443:4443'
      - '4444:4444'
